# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate quantopy-dev
#
name: quantopy-dev
channels:
  - conda-forge
dependencies:
  # required
  - python=3.8.3
  - pandas=1.2.4
  - pandas-datareader=0.9.0
  - matplotlib=3.4.2

  # code checks
  - black=21.5b2
  - flake8=3.9.2
  - flake8-bugbear=21.4.3  # used by flake8, find likely bugs
  - flake8-comprehensions=3.5.0  # used by flake8, linting of unnecessary comprehensions
  - isort=5.8.0  # check that imports are in the right order
  - mypy=0.812
  - pandas-stubs=1.1.0.1  # used by mypy
  - pycodestyle=2.7.0  # used by flake8

  # testing
  - pytest=6.2.4
  - tox-conda=0.8.0

  # notebook
  - ipykernel=5.5.5
