name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ENV_FILE: environment.yml

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: Python 3.9
            os: ubuntu-latest
            python: 3.9
            toxenv: py39

          - name: Python 3.7
            os: ubuntu-latest
            python: 3.7
            toxenv: py37

          - name: Python 3.8 with full coverage
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-cov

          - name: Python 3.8 (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov

    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}

    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
